language: android
android:
  components:
     - build-tools-23.0.1
     - build-tools-22.0.1
     - android-23
     - android-22
     - extra-google-m2repository
     - extra-android-m2repository
     - extra
before_install:
  - chmod +x gradlew
script: "./gradlew build"
